version: '3'

services:
    postgres:
        image: "postgres:15.2-alpine"
        user: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=la_libertad_app
            - POSTGRES_DB=la_libertad_app
        ports:
        - 5432:5432
        volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
